import = [
	"~/.config/alacritty/themes/themes/night_owl.toml"
]
[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
blur = true

[font]
normal = {family = "FiraCode Nerd Font Mono", style="Regular"}
size = 16
